import { chromium } from "playwright-core";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
await p.goto("http://localhost:3000/", { waitUntil: "domcontentloaded" });
await p.waitForTimeout(1500);
await p.locator("header").first().screenshot({ path: "/tmp/logo-nav.png" });
await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
await p.waitForTimeout(1200);
await p.locator("footer").first().screenshot({ path: "/tmp/logo-footer.png" }).catch(() => {});
await b.close(); console.log("ok");
